package com.letsplay.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * This class represents a Product in our application.
 * The @Document annotation tells Spring Data MongoDB that this class should be stored in a MongoDB collection.
 * The collection name is specified as "products".
 */
@Document(collection = "products")
public class Product {

    /**
     * The @Id annotation marks this field as the primary key for the documents in the collection.
     * It will be automatically generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * This field stores the name of the product.
     */
    private String name;

    /**
     * This field stores the description of the product.
     */
    private String description;

    /**
     * This field stores the price of the product.
     */
    private Double price;

    /**
     * This field stores the ID of the user who owns this product.
     * This creates a relationship between User and Product.
     */
    private String userId;

    // Getters and Setters

    /**
     * Gets the product's ID.
     * @return the product's ID.
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the product's ID.
     * @param id the product's ID.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Gets the product's name.
     * @return the product's name.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the product's name.
     * @param name the product's name.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the product's description.
     * @return the product's description.
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the product's description.
     * @param description the product's description.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets the product's price.
     * @return the product's price.
     */
    public Double getPrice() {
        return price;
    }

    /**
     * Sets the product's price.
     * @param price the product's price.
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * Gets the ID of the user who owns this product.
     * @return the user's ID.
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the ID of the user who owns this product.
     * @param userId the user's ID.
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}
