package com.letsplay.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * This class represents a User in our application.
 * The @Document annotation tells Spring Data MongoDB that this class should be stored in a MongoDB collection.
 * The collection name is specified as "users".
 */
@Document(collection = "users")
public class User {

    /**
     * The @Id annotation marks this field as the primary key for the documents in the collection.
     * It will be automatically generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * This field stores the name of the user.
     */
    private String name;

    /**
     * This field stores the email of the user. It should be unique.
     */
    private String email;

    /**
     * This field stores the hashed password of the user.
     * We should never store plain text passwords.
     */
    private String password;

    /**
     * This field stores the role of the user, e.g., "ADMIN" or "USER".
     */
    private String role;

    // Getters and Setters

    /**
     * Gets the user's ID.
     * @return the user's ID.
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the user's ID.
     * @param id the user's ID.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Gets the user's name.
     * @return the user's name.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the user's name.
     * @param name the user's name.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the user's email.
     * @return the user's email.
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the user's email.
     * @param email the user's email.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Gets the user's password.
     * @return the user's password.
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the user's password.
     * @param password the user's password.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Gets the user's role.
     * @return the user's role.
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the user's role.
     * @param role the user's role.
     */
    public void setRole(String role) {
        this.role = role;
    }
}
